apiVersion: v1
kind: Service
metadata:
  name: kanban-app
spec:
  selector:
    app: kanban-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kanban-app
  template:
    metadata:
      labels:
        app: kanban-app
    spec:
      containers:
        - name: kanban-app
          image: kanbanproject.azurecr.io/kanbanproject-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/${{ secrets.POSTGRES_DB }}
            - name: SPRING_DATASOURCE_USERNAME
              value: ${{ secrets.POSTGRES_USER }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: ${{ secrets.POSTGRES_PASSWORD }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 6

          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 200
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 6 
      imagePullSecrets:
        - name: regcred