name: Kanban CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: kanban
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: asdasd123
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'oracle'
        cache: maven

    - name: Set executable permissions for mvnw
      run: chmod +x backend/mvnw
        
    - name: Build and test backend
      run: |
        cd backend
        ./mvnw clean test jacoco:report
        
    - name: Upload test coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-coverage
        path: backend/target/site/jacoco

  frontend:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install dependencies
      run: cd frontend && npm ci
      
    - name: Build frontend
      run: cd frontend && npm run build
      
    - name: Run linting
      run: cd frontend && npm run lint
